restart_file: .na
start_datetime: 2022-07-08 00:00:00
end_datetime: .na
forecast_start_datetime: 2022-08-04 00:00:00
forecast_horizon: 0
sim_name: default_temp_oxy
configure_flare: configure_flare.yml
configure_obs: observation_processing.yml
use_s3: TRUE
