restart_file: .na
start_datetime: 2022-07-01 00:00:00
end_datetime: .na
forecast_start_datetime: 2022-07-05 00:00:00
forecast_horizon: 35
sim_name: weather_UC_OFF
configure_flare: configure_flare.yml
configure_obs: observation_processing.yml
use_s3: FALSE
